version: "3.7"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
             --init-file /innitfile/init.sql
    restart: always
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: my_crud
    volumes:
      - ./docker-config/mysql/:/innitfile
      - ./backend/database:/var/lib/mysql
      - ./docker-config/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pmypass"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  api:
    image: node
    container_name: node-container
    working_dir: /application
    entrypoint: /application/start_application.sh
    volumes:
      - ./backend:/application
      - ./docker-config/node/start_application.sh:/application/start_application.sh
    ports:
      - "8000:8000"
    depends_on:
      - db 
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
  web:
    image: nginx
    container_name: nginx-container
    working_dir: /var/www/html
    volumes:
      - ./frontend:/var/www/html
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s